# Generated by Django 2.2.9 on 2021-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedfiles/news_img/'),
        ),
    ]
