# Generated by Django 2.2.13 on 2022-03-24 03:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('danam', '0002_auto_20210110_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentOfMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='', editable=False, max_length=300)),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Curated by')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='danam-cms/', verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='danam-cms/', verbose_name='Primary Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Descriptions')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'monument-of-month',
                'verbose_name_plural': 'monument-of-months',
                'db_table': 'monument_of_month',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PdfUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Publication Date')),
                ('docfile', models.FileField(upload_to='danam_cms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pdf_uploader',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
